[workspace]

members = [
    "chip8",
    "chip8-cli",
    "chip8-win",
]

[profile.release]
# Increases runtime performance because
# LLVM has more opportunities to inline functions.
#
# Slows down compilation.
codegen-units = 1
lto = "fat"
