[package]
name = "chip8"
version = "0.1.0"
authors = ["Willem Victor <wimpievictor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chip8_core = { version = "*", path = "../chip8_core" }
chip8_bytecode = { version = "*", path = "../chip8_bytecode" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "maze"
harness = false

[features]
op_trace = ["chip8_bytecode/op_trace"]